-- Production schema for the community outage-reporting API.
-- Keep this migration in source control so a recreated Supabase project can be restored reliably.

create table if not exists public.outage_reports (
  id bigint generated by default as identity primary key,
  service_id text not null,
  problem_type text not null,
  client_hash text not null,
  country_code text not null default 'JP',
  moderation_status text not null default 'visible',
  created_at timestamptz not null default now(),

  constraint outage_reports_country_code_length
    check (char_length(country_code) = 2),
  constraint outage_reports_moderation_status
    check (moderation_status in ('visible', 'hidden', 'pending'))
);

create index if not exists outage_reports_service_created_idx
  on public.outage_reports (
    service_id,
    country_code,
    moderation_status,
    created_at desc
  );

create index if not exists outage_reports_duplicate_check_idx
  on public.outage_reports (service_id, client_hash, created_at desc);

create index if not exists outage_reports_recent_activity_idx
  on public.outage_reports (created_at desc);

alter table public.outage_reports enable row level security;

revoke all on table public.outage_reports from anon, authenticated;
revoke all on sequence public.outage_reports_id_seq from anon, authenticated;
